services:
  master:
    image: chrislusf/seaweedfs
    container_name: sw_master
    ports:
      - "9333:9333"
    command: "master -ip=master"

  volume:
    image: chrislusf/seaweedfs
    container_name: sw_volume
    ports:
      - "8080:8080"
    command: "volume -mserver=master:9333 -port=8080"
    depends_on:
      - master

  filer:
    image: chrislusf/seaweedfs
    container_name: sw_filer
    ports:
      - "8888:8888"
    command: "filer -master=master:9333"
    depends_on:
      - master
      - volume

  s3:
    image: chrislusf/seaweedfs
    container_name: sw_s3
    ports:
      - "8333:8333"
    volumes:
      - ./s3.json:/etc/seaweedfs/s3.json
    command: 's3 -filer="filer:8888" -ip.bind=0.0.0.0 -config="/etc/seaweedfs/s3.json"'
    depends_on:
      - filer

  postgres:
    image: postgres:16
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: dms
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U myuser -d dms" ]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: .
    container_name: backend
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://myuser:mypassword@postgres:5432/dms
      S3_ENDPOINT: http://s3:8333
      S3_ACCESS_KEY: mykey
      S3_SECRET_KEY: mysecret
      EMAIL_ENCRYPTION_KEY: L2II5RV2sn9EPmWoq1tdfHIN2wwntQfXeKLMG4lPbCc=
    depends_on:
      postgres:
        condition: service_healthy
      s3:
        condition: service_started
    volumes:
      - ./app:/app/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  frontend:
    build:
      context: ./frontend
      args:
        VITE_API_URL: http://localhost:8000
    container_name: frontend
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  postgres_data:
