apiVersion: v1
kind: Service
metadata:
  name: tika
  namespace: dms
spec:
  selector:
    app: tika
  ports:
    - port: 9998
      targetPort: 9998
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tika
  namespace: dms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tika
  template:
    metadata:
      labels:
        app: tika
    spec:
      containers:
        - name: tika
          image: apache/tika:latest
          ports:
            - containerPort: 9998
          resources:
            requests: { cpu: "100m", memory: "512Mi" }
            limits: { cpu: "1000m", memory: "1Gi" }
